# Generated by Django 5.1.4 on 2025-02-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('ipam', '0076_natural_ordering'),
        ('netbox_sm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='ipam.prefix'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_vlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='ipam.vlan'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='ipam.prefix'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_vlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='ipam.vlan'),
        ),
    ]