# Generated by Django 5.0.9 on 2024-10-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_servicemgmt', '0002_alter_faulttolerance_options_and_more'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetemplate',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='solutiondeployment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='solutiontemplate',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='solutiontemplate',
            name='business_owner_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_business_owners', to='tenancy.contact'),
        ),
        migrations.AddField(
            model_name='solutiontemplate',
            name='business_owner_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_business_owners', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='solutiontemplate',
            name='solution_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]