# Generated by Django 5.0.9 on 2024-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_servicemgmt', '0003_alter_servicetemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetemplate',
            name='solution_template',
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='solution_templates',
            field=models.ManyToManyField(related_name='service_templates', to='netbox_servicemgmt.solutiontemplate'),
        ),
    ]