# Generated by Django 5.0.9 on 2024-10-22 00:06

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_servicemgmt', '0004_remove_servicetemplate_solution_template_and_more'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedeployment',
            name='solution_deployment',
        ),
        migrations.AddField(
            model_name='servicecomponent',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='netbox_servicemgmt.servicecomponent'),
        ),
        migrations.AddField(
            model_name='servicecomponent',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecomponent',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicedeployment',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='netbox_servicemgmt.servicedeployment'),
        ),
        migrations.AddField(
            model_name='servicedeployment',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='servicedeployment',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='netbox_servicemgmt.servicerequirement'),
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequirement',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='netbox_servicemgmt.servicetemplate'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solutiontemplate',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='netbox_servicemgmt.solutiontemplate'),
        ),
        migrations.AddField(
            model_name='solutiontemplate',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='solutiontemplate',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicecomponent',
            name='service_deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_deployments', to='netbox_servicemgmt.servicedeployment'),
        ),
        migrations.CreateModel(
            name='SolutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('solution_type', models.CharField(max_length=255, null=True)),
                ('requirements', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='inactive', max_length=20)),
                ('business_owner_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sreq_business_owners', to='tenancy.contact')),
                ('business_owner_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sreq_business_owners', to='tenancy.tenant')),
                ('design_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sreq_designers', to='tenancy.contact')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='netbox_servicemgmt.solutionrequest')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Solution Request',
                'verbose_name_plural': 'Solution Requests',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='solutiontemplate',
            name='solution_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_templates', to='netbox_servicemgmt.solutionrequest'),
        ),
        migrations.DeleteModel(
            name='SolutionDeployment',
        ),
    ]