# Generated by Django 5.0.9 on 2024-10-19 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0191_module_bay_rebuild'),
        ('netbox_servicemgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faulttolerance',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='servicecomponent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='slo',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='slo',
            name='sev3_response',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='airgap_backup',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='backup_schedule',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='clustered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='instances_per_site',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='multi_region',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='multi_site',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='offsite_backup',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='offsite_replication',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='secondary_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ft_secondary_sites', to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='snapshots',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='tertiary_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ft_tertiary_sites', to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='faulttolerance',
            name='vip_required',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='servicecomponent',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='slo',
            name='sev1_response',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slo',
            name='sev2_response',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]